const std = @import("std");
const builtin = @import("builtin");

fn linkPlatformLibs(compile: *std.Build.Step.Compile, target: std.Build.ResolvedTarget) void {
    compile.root_module.link_libc = true;
    if (target.result.os.tag == .windows) {
        // Winsock symbols are provided by these system libraries on Windows.
        compile.root_module.linkSystemLibrary("ws2_32", .{});
        compile.root_module.linkSystemLibrary("mswsock", .{});
    }
}

/// Recursively embeds a directory into an executable at build time.
///
/// Walks `root_dir` (relative to the project root) with the host
/// filesystem, sorts entries deterministically by relative path, reads
/// every file, and generates a manifest module importable as
/// `import_name`:
///
/// ```zig
/// const embedded = @import("embed_website");
/// try httpx.assets.registerEmbeddedDir(allocator, &embedded.files);
/// ```
///
/// `embedded.files` matches `httpx.assets.EmbeddedFile`
/// (`{ path, content }`), so one call registers the whole tree. Logical
/// paths are portable `/`-separated relatives and file bytes are inlined
/// as escaped string literals, keeping the generated manifest portable
/// across machines. MIME types and sizes derive at runtime through the
/// shared MIME system and `content.len` (single source of truth).
/// Asset names containing `"` and files over 16 MiB are skipped.
fn embedDir(b: *std.Build, exe: *std.Build.Step.Compile, httpx_module: *std.Build.Module, root_dir: []const u8, import_name: []const u8) void {
    const allocator = b.allocator;
    var rel_paths: std.ArrayList([]u8) = .empty;
    defer {
        for (rel_paths.items) |p| allocator.free(p);
        rel_paths.deinit(allocator);
    }

    const io = b.graph.io;
    const cwd: std.Io.Dir = .cwd();
    var root = cwd.openDir(io, root_dir, .{ .iterate = true }) catch return;
    defer root.close(io);
    var walker = root.walk(allocator) catch return;
    defer walker.deinit();
    while (walker.next(io) catch null) |entry| {
        if (entry.kind != .file) continue;
        var p = allocator.dupe(u8, entry.path) catch return;
        for (p, 0..) |_, i| {
            if (p[i] == '\\') p[i] = '/';
        }
        if (std.mem.indexOfScalar(u8, p, '"') != null) continue;
        rel_paths.append(allocator, p) catch return;
    }
    std.mem.sort([]u8, rel_paths.items, {}, struct {
        fn less(_: void, x: []u8, y: []u8) bool {
            return std.mem.order(u8, x, y) == .lt;
        }
    }.less);

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);
    out.print(allocator, "// Generated by build.zig embedDir from \"{s}\" - do not edit.\n", .{root_dir}) catch return;
    out.appendSlice(allocator, "const httpx = @import(\"httpx\");\n") catch return;
    out.appendSlice(allocator, "pub const files = [_]httpx.assets.EmbeddedFile{\n") catch return;
    for (rel_paths.items) |rel| {
        const content = root.readFileAlloc(io, rel, allocator, .limited(16 * 1024 * 1024)) catch continue;
        defer allocator.free(content);
        out.print(allocator, "    .{{ .path = \"{s}\", .content = \"", .{rel}) catch return;
        for (content) |c| {
            switch (c) {
                '\n' => out.appendSlice(allocator, "\\n") catch return,
                '\r' => out.appendSlice(allocator, "\\r") catch return,
                '\t' => out.appendSlice(allocator, "\\t") catch return,
                0x20...0x7e => {
                    if (c == '"' or c == '\\') {
                        out.print(allocator, "\\{c}", .{c}) catch return;
                    } else {
                        out.append(allocator, c) catch return;
                    }
                },
                else => out.print(allocator, "\\x{x:0>2}", .{c}) catch return,
            }
        }
        out.appendSlice(allocator, "\" },\n") catch return;
    }
    out.appendSlice(allocator, "};\n") catch return;

    const wf = b.addWriteFiles();
    const manifest_name = std.fmt.allocPrint(allocator, "{s}.zig", .{import_name}) catch return;
    _ = wf.add(manifest_name, out.items);
    exe.root_module.addAnonymousImport(import_name, .{
        .root_source_file = wf.getDirectory().path(b, manifest_name),
        .imports = &.{
            .{ .name = "httpx", .module = httpx_module },
        },
    });
}

/// Build configuration for httpx.zig - Production-ready HTTP library for Zig
/// Supports HTTP/1.1, HTTP/2, HTTP/3 with TLS, connection pooling, and more.
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});

    const optimize = b.standardOptimizeOption(.{});

    const zstd_dep = b.dependency("zstd", .{
        .target = target,
        .optimize = optimize,
    });

    const brotli_dep = b.dependency("brotli", .{
        .target = target,
        .optimize = optimize,
    });

    const env_dep = b.dependency("env", .{
        .target = target,
        .optimize = optimize,
    });

    const loaders_dep = b.dependency("loaders", .{
        .target = target,
        .optimize = optimize,
    });

    const treesitter_dep = b.dependency("treesitter", .{
        .target = target,
        .optimize = optimize,
    });

    // Create the public module that will be exported as "httpx" to consumers.
    // Dependencies must be added here so they propagate to downstream packages.
    const httpx_module = b.addModule("httpx", .{
        .root_source_file = b.path("src/httpx.zig"),
    });

    httpx_module.addImport("zstd", zstd_dep.module("zstd"));
    httpx_module.addImport("brotli", brotli_dep.module("brotli"));
    httpx_module.addImport("env", env_dep.module("env"));
    httpx_module.addImport("loaders", loaders_dep.module("loaders"));
    httpx_module.addImport("treesitter", treesitter_dep.module("treesitter"));

    const examples = [_]struct { name: []const u8, path: []const u8 }{
        .{ .name = "simple-get", .path = "examples/simple_get.zig" },
        .{ .name = "post-json", .path = "examples/post_json.zig" },
        .{ .name = "custom-headers", .path = "examples/custom_headers.zig" },
        .{ .name = "connection-pool", .path = "examples/connection_pool.zig" },
        .{ .name = "redirect", .path = "examples/redirect.zig" },
        .{ .name = "streaming", .path = "examples/streaming.zig" },
        .{ .name = "multipart", .path = "examples/multipart.zig" },
        .{ .name = "custom-responses", .path = "examples/custom_responses.zig" },
        .{ .name = "browser-demo-server", .path = "examples/browser_demo_server.zig" },
        .{ .name = "simple-server", .path = "examples/simple_server.zig" },
        .{ .name = "static-files", .path = "examples/static_files.zig" },
        .{ .name = "health-check", .path = "examples/health_check.zig" },
        .{ .name = "tls-get", .path = "examples/tls_get.zig" },
        .{ .name = "resolve", .path = "examples/resolve.zig" },
        .{ .name = "openapi", .path = "examples/openapi.zig" },
        .{ .name = "http10-client", .path = "examples/http10_client.zig" },
        .{ .name = "http11-client", .path = "examples/http11_client.zig" },
        .{ .name = "http11-server", .path = "examples/http11_server.zig" },
        .{ .name = "http2-client", .path = "examples/http2_client.zig" },
        .{ .name = "http2-multiplex", .path = "examples/http2_multiplex.zig" },
        .{ .name = "http3-client", .path = "examples/http3_client.zig" },
        .{ .name = "http3-quic", .path = "examples/http3_quic.zig" },
        .{ .name = "ftp-client", .path = "examples/ftp_client.zig" },
        .{ .name = "live-static-watcher", .path = "examples/live_static_watcher.zig" },
        .{ .name = "docs-server", .path = "examples/docs_server.zig" },
        .{ .name = "graphql-server", .path = "examples/graphql_server.zig" },
        .{ .name = "auth-and-errors", .path = "examples/auth_and_errors.zig" },
        .{ .name = "spa-fallback", .path = "examples/spa_fallback.zig" },
        .{ .name = "websocket-server", .path = "examples/websocket_server.zig" },
        .{ .name = "sse-server", .path = "examples/sse_server.zig" },
        .{ .name = "session-server", .path = "examples/session_server.zig" },
        .{ .name = "metrics-server", .path = "examples/metrics_server.zig" },
        .{ .name = "interceptor-example", .path = "examples/interceptor_example.zig" },
        .{ .name = "cookie-server", .path = "examples/cookie_server.zig" },
        .{ .name = "concurrent-demo", .path = "examples/concurrent_demo.zig" },
        .{ .name = "proxy-demo", .path = "examples/proxy_demo.zig" },
        .{ .name = "dns-demo", .path = "examples/dns_demo.zig" },
        .{ .name = "compression-demo", .path = "examples/compression_demo.zig" },
        .{ .name = "retry-demo", .path = "examples/retry_demo.zig" },
        .{ .name = "custom-server", .path = "examples/custom_server.zig" },
        .{ .name = "cors-server", .path = "examples/cors_server.zig" },
        .{ .name = "rate-limit-server", .path = "examples/rate_limit_server.zig" },
        .{ .name = "helmet-server", .path = "examples/helmet_server.zig" },
        .{ .name = "body-parser-server", .path = "examples/body_parser_server.zig" },
        .{ .name = "tls-server", .path = "examples/tls_server.zig" },
        .{ .name = "https-client", .path = "examples/https_client.zig" },
        .{ .name = "tls12-client", .path = "examples/tls12_client.zig" },
        .{ .name = "tls13-client", .path = "examples/tls13_client.zig" },
        .{ .name = "tls-mtls", .path = "examples/tls_mtls.zig" },
        .{ .name = "dns-cache", .path = "examples/dns_cache.zig" },
        .{ .name = "ftp-server", .path = "examples/ftp_server.zig" },
        .{ .name = "download", .path = "examples/download.zig" },
        .{ .name = "download-info", .path = "examples/download_info.zig" },
        .{ .name = "download-verify", .path = "examples/download_verify.zig" },
        .{ .name = "download-resume", .path = "examples/download_resume.zig" },
        .{ .name = "download-existing", .path = "examples/download_existing.zig" },
        .{ .name = "download-custom-progress", .path = "examples/download_custom_progress.zig" },
        .{ .name = "download-batch", .path = "examples/download_batch.zig" },
        .{ .name = "download-update", .path = "examples/download_update.zig" },
        .{ .name = "download-checksum-file", .path = "examples/download_checksum_file.zig" },
        .{ .name = "ftp-download", .path = "examples/ftp_download.zig" },
        .{ .name = "parse-html", .path = "examples/parse_html.zig" },
        .{ .name = "html-client", .path = "examples/html_client.zig" },
        .{ .name = "html-select", .path = "examples/html_select.zig" },
        .{ .name = "html-extract", .path = "examples/html_extract.zig" },
        .{ .name = "html-stream", .path = "examples/html_stream.zig" },
        .{ .name = "html-file", .path = "examples/html_file.zig" },
        .{ .name = "html-transform", .path = "examples/html_transform.zig" },
        .{ .name = "file-watcher", .path = "examples/file_watcher.zig" },
        .{ .name = "live-reload", .path = "examples/live_reload.zig" },
        .{ .name = "static-site", .path = "examples/static_site.zig" },
        .{ .name = "static-embedded", .path = "examples/static_embedded.zig" },
        .{ .name = "spa-server", .path = "examples/spa_server.zig" },
        .{ .name = "development-server", .path = "examples/development_server.zig" },
        .{ .name = "connectivity", .path = "examples/connectivity.zig" },
        .{ .name = "full-integration", .path = "examples/full_integration.zig" },
        .{ .name = "template-basic", .path = "examples/web/templates/basic/main.zig" },
        .{ .name = "template-inheritance", .path = "examples/web/templates/inheritance/main.zig" },
        .{ .name = "template-loops", .path = "examples/web/templates/loops/main.zig" },
        .{ .name = "template-includes", .path = "examples/web/templates/includes/main.zig" },
        .{ .name = "template-live-reload", .path = "examples/web/templates/live_reload/main.zig" },
        .{ .name = "website", .path = "examples/website/main.zig" },
    };

    const build_all_examples = b.step("build-all-examples", "Build all example executables");

    inline for (examples) |example| {
        const exe = b.addExecutable(.{
            .name = example.name,
            .root_module = b.createModule(.{
                .root_source_file = b.path(example.path),
                .target = target,
                .optimize = optimize,
            }),
        });
        exe.root_module.addImport("httpx", httpx_module);
        linkPlatformLibs(exe, target);
        if (comptime std.mem.eql(u8, example.name, "website")) {
            embedDir(b, exe, httpx_module, "examples/website/dist", "embed_website");
        }

        const install_exe = b.addInstallArtifact(exe, .{});
        build_all_examples.dependOn(&install_exe.step);
        const example_step = b.step("example-" ++ example.name, "Build " ++ example.name ++ " example");
        example_step.dependOn(&install_exe.step);

        const run_exe = b.addRunArtifact(exe);
        run_exe.step.dependOn(&install_exe.step);
        const run_step = b.step("run-" ++ example.name, "Run " ++ example.name ++ " example");
        run_step.dependOn(&run_exe.step);
    }

    const run_all_examples = b.step("run-all-examples", "Run all examples sequentially");
    var previous_run_step: ?*std.Build.Step = null;

    inline for (examples) |example| {
        const exe = b.addExecutable(.{
            .name = "run-all-" ++ example.name,
            .root_module = b.createModule(.{
                .root_source_file = b.path(example.path),
                .target = target,
                .optimize = optimize,
            }),
        });
        exe.root_module.addImport("httpx", httpx_module);
        linkPlatformLibs(exe, target);
        if (comptime std.mem.eql(u8, example.name, "website")) {
            embedDir(b, exe, httpx_module, "examples/website/dist", "embed_website");
        }

        const install_exe = b.addInstallArtifact(exe, .{});
        if (previous_run_step) |prev| {
            exe.step.dependOn(prev);
            install_exe.step.dependOn(prev);
        }
        const run_exe = b.addRunArtifact(exe);
        run_exe.step.dependOn(&install_exe.step);

        previous_run_step = &run_exe.step;
    }

    if (previous_run_step) |last| {
        run_all_examples.dependOn(last);
    }

    const tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/httpx.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    tests.root_module.addImport("zstd", zstd_dep.module("zstd"));
    tests.root_module.addImport("brotli", brotli_dep.module("brotli"));
    tests.root_module.addImport("env", env_dep.module("env"));
    tests.root_module.addImport("loaders", loaders_dep.module("loaders"));
    tests.root_module.addImport("treesitter", treesitter_dep.module("treesitter"));
    linkPlatformLibs(tests, target);

    const run_tests = b.addRunArtifact(tests);
    run_tests.has_side_effects = true;
    const test_step = b.step("test", "Run unit tests");

    // Only run tests when target matches host; otherwise build test artifact only.
    if (target.result.os.tag == builtin.os.tag and target.result.cpu.arch == builtin.cpu.arch) {
        test_step.dependOn(&run_tests.step);
    } else {
        const install_tests = b.addInstallArtifact(tests, .{});
        test_step.dependOn(&install_tests.step);
    }

    const bench_exe = b.addExecutable(.{
        .name = "benchmark",
        .root_module = b.createModule(.{
            .root_source_file = b.path("bench/main.zig"),
            .target = target,
            .optimize = .ReleaseFast,
        }),
    });
    bench_exe.root_module.addImport("httpx", httpx_module);
    linkPlatformLibs(bench_exe, target);

    const install_bench = b.addInstallArtifact(bench_exe, .{});
    const run_bench = b.addRunArtifact(bench_exe);
    run_bench.step.dependOn(&install_bench.step);

    const bench_step = b.step("bench", "Run benchmarks");
    bench_step.dependOn(&run_bench.step);

    const lib_root_module = b.createModule(.{
        .root_source_file = b.path("src/httpx.zig"),
        .target = target,
        .optimize = optimize,
    });
    lib_root_module.addImport("zstd", zstd_dep.module("zstd"));
    lib_root_module.addImport("brotli", brotli_dep.module("brotli"));
    lib_root_module.addImport("env", env_dep.module("env"));
    lib_root_module.addImport("loaders", loaders_dep.module("loaders"));
    lib_root_module.addImport("treesitter", treesitter_dep.module("treesitter"));

    const lib = b.addLibrary(.{
        .name = "httpx",
        .linkage = .static,
        .root_module = lib_root_module,
    });
    linkPlatformLibs(lib, target);

    b.installArtifact(lib);

    const docs_step = b.step("docs", "Generate library documentation");
    const install_docs = b.addInstallDirectory(.{
        .source_dir = lib.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs",
    });
    docs_step.dependOn(&install_docs.step);

    const test_all_step = b.step("test-all", "Run tests, benchmarks, and all runnable examples");
    test_all_step.dependOn(test_step);
    test_all_step.dependOn(bench_step);
    test_all_step.dependOn(run_all_examples);
}
